### ISSUE TITLE
Bounty for b2 flysystem adapter

### ISSUE THREAD

**Issue by Mark-H** [gliterd/flysystem-backblaze#4]
Hiya!

Just to let you know, there's a small bug bounty at https://www.bountysource.com/issues/26874333-backblaze-b2-adapter for implementation of B2 into flysystem... looks like you're the first to publish something that's in progress, so feel free to claim it once the basic functionality is in place ;)

**Comment by mhetreramesh** [comment]
Hey Mark, 
Thanks for the info. Sorry about the late reply. My package is already being listed on thephphpleague site. Here is the link: https://github.com/thephpleague/flysystem

**Comment by Mark-H** [comment]
Looks like there's a couple of methods that don't do anything yet.. read, readStream, rename, getMetaData and getMimetype methods just return false. Are you planning to add those? Especially the read and metadata ones seem rather important ;)

**Comment by mhetreramesh** [comment]
Yes, I'm planning to work on that in next couple of weeks. So hope, it would be done in a while.

**Comment by cyimking** [comment]
@mhetreramesh - Did you complete getMetaData() function? Unless I did something completely wrong, files can not be deleted since getMetadata() returns false. 

I was able to get it working via...
` 
public function getMetadata($path)
    {
        $file = $this->getClient()->getFile(['FileName' => $path, 'BucketName' => $this->bucketName]);

        return $this->getFileInfo($file);
    }
`

**Comment by mhetreramesh** [comment]
@cyimking I don't remember changing anything on the code. Seems like this part was pending to implement & I'm not actively using Blackbaze now. Would be great for others too if you just send a PR.
